--- 
apiVersion: v1
kind: Template
metadata: 
  annotations: 
    description: "docker nodejs application"
    tags: "${APP_NAME}"
  name: "${APP_NAME}"
objects: 
  - 
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata: 
      labels: 
        app: "${APP_NAME}"
      name: default_view
    roleRef: 
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: view
    subjects: 
      - 
        kind: ServiceAccount
        name: default
  - 
    apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata: 
      labels: 
        app: "${APP_NAME}"
      name: "${APP_NAME}"
    spec: 
      tags: 
        - 
          name: latest
  - 
    apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata: 
      labels: 
        app: "${APP_NAME}"
      name: "${APP_NAME}"
    spec: 
      output: 
        to: 
          kind: ImageStreamTag
          name: "${APP_NAME}:latest"
      runPolicy: Serial
      source: 
        contextDir: /
        git: 
          ref: "${GIT_REF}"
          uri: "${GIT_URL}"
        type: Git
      strategy: 
        sourceStrategy: 
          from: 
            kind: ImageStreamTag
            name: "nodejs:latest"
            namespace: openshift
        type: Source
  - 
    apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata: 
      labels: 
        build: "${APP_NAME}-${GIT_REF}-git"
      name: "${APP_NAME}-${GIT_REF}-git"
    spec: 
      runPolicy: Serial
      source: 
        git: 
          ref: "${GIT_REF}"
          uri: "${GIT_URL}"
        type: Git
      triggers: 
        - 
          type: ConfigChange
        - 
          github: 
            secret: lNW-G9fDOk--MYJ3iNK1
          type: GitHub
        - 
          generic: 
            secret: ZSyQC2Cy7nc6fMxZJMZi
          type: Generic
  - 
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata: 
      annotations: 
        app.openshift.io/vcs-ref: "${GIT_REF}"
        app.openshift.io/vcs-uri: "${GIT_URL}"
      labels: 
        app: "${APP_NAME}"
        app.kubernetes.io/part-of: "${APP_NAME}"
        app.openshift.io/runtime: nodejs
        app.openshift.io/runtime-version: "10"
      name: "${APP_NAME}"
    spec: 
      replicas: 1
      selector: 
        deploymentconfig: "${APP_NAME}"
      strategy: 
        type: Recreate
      template: 
        metadata: 
          labels: 
            app: "${APP_NAME}"
            deploymentconfig: "${APP_NAME}"
        spec: 
          containers: 
            - 
              image: "${APP_NAME}:latest"
              imagePullPolicy: Always
              name: "${APP_NAME}"
              ports: 
                - 
                  containerPort: 8080
                  protocol: TCP
      triggers: 
        - 
          type: ConfigChange
        - 
          imageChangeParams: 
            automatic: true
            containerNames: 
              - "${APP_NAME}"
            from: 
              kind: ImageStreamTag
              name: "${APP_NAME}:latest"
          type: ImageChange
  - 
    apiVersion: v1
    kind: Service
    metadata: 
      labels: 
        app: "${APP_NAME}"
      name: "${APP_NAME}"
    spec: 
      ports: 
        - 
          name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
        - 
          name: 8443-tcp
          port: 8443
          protocol: TCP
          targetPort: 8443
        - 
          name: 8778-tcp
          port: 8778
          protocol: TCP
          targetPort: 8778
      selector: 
        deploymentconfig: "${APP_NAME}"
  - 
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata: 
      labels: 
        app: "${APP_NAME}"
      name: "${APP_NAME}"
    spec: 
      port: 
        targetPort: 8080-tcp
      to: 
        kind: Service
        name: "${APP_NAME}"
        weight: 100
parameters: 
  - 
    description: "The name of the application"
    name: APP_NAME
    required: true
    value: dockernodejs
  - 
    description: "The git url to build from"
    name: GIT_URL
    required: true
    value: ""
  - 
    description: "The git branch/tag to pull from"
    name: GIT_REF
    required: true
    value: master
  - 
    description: "project or namespace"
    name: PROJECT
    required: true
    value: cicdrelease
